---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongo-mck-ca-crt
  namespace: "{{mongodb_mck_namespace}}"
spec:
  isCA: true
  commonName: mongo-mck-ca-crt
  secretName: mongo-mck-ca-secret
  duration: 175200h # 20 years
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - "*.mas-mongo-mck-svc.{{mongodb_mck_namespace}}.svc.cluster.local"
    - "127.0.0.1"
    - "localhost"
  issuerRef:
    name: mongo-mck-issuer
    kind: Issuer
    group: cert-manager.io
