apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongo-mck-server
  namespace: "{{mongodb_mck_namespace}}"
spec:
  duration: 8760h # 365d
  renewBefore: 360h # 15d
  dnsNames:
    - "*.mas-mongo-mck-svc.{{mongodb_mck_namespace}}.svc.cluster.local"
    - "127.0.0.1"
    - "localhost"

  issuerRef:
    name: mongo-mck-server-cert-issuer
  secretName: mongo-mck-server-cert
