---
# 1. Load default settings
# -----------------------------------------------------------------------------
- name: "Determine Version of Maximo Operator Catalog"
  include_tasks: "{{ role_path }}/../../common_tasks/determine-ibmcatalog-tag.yml"

- name: Load Catalog Metadata
  when:
    - mongo_mck_extras_version is not defined or mongo_mck_extras_version == ""
    - catalog_tag is defined and catalog_tag != ""
  block:
    - ibm.mas_devops.get_catalog_info:
        mas_catalog_version: "{{ catalog_tag }}"
      register: _mas_catalog
    - debug:
        var: _mas_catalog
    - name: "Set mongo version to default value if not explicitly set"
      set_fact:
        mongo_mck_extras_version: "{{ _mas_catalog.mongo_mck_extras_version_default }}"

- name: "Mongo Version"
  debug:
    msg:
      - "Maximo Operator Catalog .................. {{ catalog_tag }}"
      - "Mongo Version ............................ {{ mongo_mck_extras_version }}"

- name: Load mongo defaults
  include_vars:
    file: "{{ role_path }}/../mirror_extras_prepare/vars/mongomck_{{ mongo_extras_version }}.yml"

- name: Retrieve image setting parts
  set_fact:
    mongodb_mck_operator_image_name: "{{ extra_images | selectattr('name', 'match', '.*/mongodb-kubernetes-operator$') | map(attribute='name') | first }}"
    mongodb_mck_operator_image_registry: "{{ extra_images | selectattr('name', 'match', '.*/mongodb-kubernetes-operator$') | map(attribute='registry') | first }}"
    mongodb_mck_operator_image_digest: "{{ extra_images | selectattr('name', 'match', '.*/mongodb-kubernetes-operator$') | map(attribute='digest') | first }}"
    mongodb_mck_operator_image_tag: "{{ extra_images | selectattr('name', 'match', '.*/mongodb-kubernetes-operator$') | map(attribute='tag') | first }}"
    mongodb_mck_operator_version_upgrade_post_start_hook_image_name: "{{ extra_images | selectattr('name', 'match', '.*/mongodb-kubernetes-operator-version-upgrade-post-start-hook$') | map(attribute='name') | first }}"
    mongodb_mck_operator_version_upgrade_post_start_hook_image_registry: "{{ extra_images | selectattr('name', 'match', '.*/mongodb-kubernetes-operator-version-upgrade-post-start-hook$') | map(attribute='registry') | first }}"
    mongodb_mck_operator_version_upgrade_post_start_hook_image_digest: "{{ extra_images | selectattr('name', 'match', '.*/mongodb-kubernetes-operator-version-upgrade-post-start-hook$') | map(attribute='digest') | first }}"
    mongodb_mck_agent_image_name: "{{ extra_images | selectattr('name', 'match', '.*/mongodb-agent$') | map(attribute='name') | first }}"
    mongodb_mck_agent_image_registry: "{{ extra_images | selectattr('name', 'match', '.*/mongodb-agent$') | map(attribute='registry') | first }}"
    mongodb_mck_agent_image_digest: "{{ extra_images | selectattr('name', 'match', '.*/mongodb-agent$') | map(attribute='digest') | first }}"
    mongodb_mck_readinessprobe_image_name: "{{ extra_images | selectattr('name', 'match', '.*/mongodb-kubernetes-readinessprobe$') | map(attribute='name') | first }}"
    mongodb_mck_readinessprobe_image_registry: "{{ extra_images | selectattr('name', 'match', '.*/mongodb-kubernetes-readinessprobe$') | map(attribute='registry') | first }}"
    mongodb_mck_readinessprobe_image_digest: "{{ extra_images | selectattr('name', 'match', '.*/mongodb-kubernetes-readinessprobe$') | map(attribute='digest') | first }}"
    mongodb_mck_image_name: "{{ extra_images | selectattr('name', 'match', '.*/mongodb-kubernetes$') | map(attribute='name') | first }}"
    mongodb_mck_image_registry: "{{ extra_images | selectattr('name', 'match', '.*/mongodb-kubernetes$') | map(attribute='registry') | first }}"
    mongodb_mck_image_digest: "{{ extra_images | selectattr('name', 'match', '.*/mongodb-kubernetes$') | map(attribute='digest') | first }}"

- name: Construct image full image settings
  set_fact:
    target_mongodb_mck_version: "{{ mongo_mck_extras_version}}"
    mongodb_feature_compatibility_version: "{{ mongo_mck_extras_version | regex_search('(?<=)(.*)(?=...)') }}"
    mongodb_mck_version: "{{ mongodb_mck_operator_image_tag }}"
    target_mongodb_mck_operator_image: "{{ mongodb_mck_operator_image_registry }}/{{ mongodb_mck_operator_image_name }}@{{ mongodb_mck_operator_image_digest }}"
    target_mongodb_mck_operator_version_upgrade_post_start_hook_image: "{{ mongodb_mck_operator_version_upgrade_post_start_hook_image_registry }}/{{ mongodb_mck_operator_version_upgrade_post_start_hook_image_name }}@{{ mongodb_mck_operator_version_upgrade_post_start_hook_image_digest }}"
    target_mongodb_mck_agent_image: "{{ mongodb_mck_agent_image_registry }}/{{ mongodb_mck_agent_image_name }}@{{ mongodb_mck_agent_image_digest }}"
    target_mongodb_mck_readinessprobe_image: "{{ mongodb_mck_readinessprobe_image_registry }}/{{ mongodb_mck_readinessprobe_image_name }}@{{ mongodb_mck_readinessprobe_image_digest }}"
    target_mongodb_mck_image: "{{ mongodb_mck_image_registry }}/{{ mongodb_mck_image_name }}@{{ mongodb_mck_image_digest }}"

# 2. Debug Properties
# -----------------------------------------------------------------------------
- name: "community : install : Debug properties"
  debug:
    msg:
      - "MongoDb namespace ......................... {{ mongodb_mck_namespace }}"
      - "MongoDb operator version .................. {{ mongodb_mck_version }}"
      - "MongoDb data capacity ..................... {{ mongodb_mck_storage_capacity_data }}"
      - "MongoDb logs capacity ..................... {{ mongodb_mck_storage_capacity_logs }}"
      - "MongoDb replicas .......................... {{ mongodb_mck_replicas }}"
      - "MongoDb version ........................... {{ target_mongodb_mck_version }}"
      - "MongoDb feature compatibility version ..... {{ mongodb_mck_feature_compatibility_version }}"
      - "MAS instance ID ........................... {{ mas_instance_id | default('<undefined>', True) }}"
      - "MAS config directory ...................... {{ mas_config_dir | default('<undefined>', True)  }}"
      - "Override Spec over existing MongoDB ....... {{ mongodb_mck_override_spec }}"

# Validate if upgrade has been issued by user
# Only needed when there is an existing mongo instance and its version does not match with the target version to be installed
- name: "mck: install : validate upgrade process"
  include_tasks: tasks/providers/mck/validate-upgrade.yml
  when:
    - existing_mongodb.resources[0].spec.version is defined
    - existing_mongodb.resources[0].spec.version != target_mongodb_version

- name: "mck : install : begin controlled upgrade process"
  include_tasks: tasks/providers/mck/controlled-upgrade.yml
  vars:
    current_mongodb_version: "{{ existing_mongodb.resources[0].spec.version }}"
    current_mongodb_image: "{{ existing_mongodb.resources[0].spec.statefulSet.spec.template.spec.containers[0].image }}"
    current_mongo_operator_image: "{{ existing_mongo_operator.resources[0].spec.containers[0].image }}"
  when:
    - not controlled_upgrade
    - existing_mongodb is defined
    - existing_mongodb.resources[0] is defined
    - existing_mongodb.resources[0].spec.version is defined
    - existing_mongodb.resources[0].spec.version != target_mongodb_version
    - existing_mongo_operator is defined
    - existing_mongo_operator.resources[0] is defined
    - existing_mongo_operator.resources[0].spec.containers[0].image != target_mongodb_operator_image

# 3. Install the CRD ( MCK Community)
# -----------------------------------------------------------------------------
- name: "mck : install : Install MongoDB Community CRDs"
  kubernetes.core.k8s:
    apply: yes
    template: "templates/mck/{{ mongodb_mck_version }}//crd_mongocommunity.yml.j2"
    

# 4. Install the CRD ( MCK Search )
# -----------------------------------------------------------------------------
- name: "mck : install : Install MongoDB Search CRDs"
  kubernetes.core.k8s:
    apply: yes
    template: "templates/mck/{{ mongodb_mck_version }}///crd_mongosearch.yml.j2"

# 5. Create namespace & install RBAC (MCK)
# -----------------------------------------------------------------------------
- name: "mck : install : Create namespace & install RBAC"
  kubernetes.core.k8s:
    apply: yes
    template: "templates/mck/{{ mongodb_mck_version }}///rbac.yml.j2"

# 5. Configure anyuid permissions in the MongoDb namespace
# -----------------------------------------------------------------------------
- name: "mck : install : Configure anyuid permissions in the MongoDb namespace"
  shell: |
    oc adm policy add-scc-to-user anyuid system:serviceaccount:{{ mongodb_mck_namespace }}:default
    oc adm policy add-scc-to-user anyuid system:serviceaccount:{{ mongodb_mck_namespace }}:mongodb-kubernetes-operator
    oc adm policy add-scc-to-user anyuid system:serviceaccount:{{ mongodb_mck_namespace }}:mongodb-kubernetes-appdb
    oc adm policy add-scc-to-user anyuid system:serviceaccount:{{ mongodb_mck_namespace }}:mongodb-database

# 6. Install the operator
# -----------------------------------------------------------------------------o
- name: "mck : install : Install the MongoDB Kubernetes Operator"
  kubernetes.core.k8s:
    apply: yes
    template: "templates/{{ mongodb_mck_version }}///manager.yml.j2"
    wait: yes
    wait_condition:
      status: "True"
      type: Available

# 7. Configure TLS using cert-manager (MCK)
# -----------------------------------------------------------------------------
- name: "mck : tls : Create CA Issuer in '{{ mongodb_mck_namespace }}' namespace"
  kubernetes.core.k8s:
    apply: yes
    template: "templates/mck/issuer.yml"
    wait: yes
    wait_condition:
      status: "True"
      type: Ready

- name: "mck : tls : Create CA certificate in '{{ mongodb_mck_namespace }}' namespace"
  kubernetes.core.k8s:
    apply: yes
    template: "templates/mck/ca-cert.yml"
    wait: yes
    wait_condition:
      status: "True"
      type: Ready

- name: "mck : tls : Create server certificate Issuer in '{{ mongodb_mck_namespace }}' namespace"
  kubernetes.core.k8s:
    apply: yes
    template: "templates/mck/server-cert-issuer.yml"
    wait: yes
    wait_condition:
      status: "True"
      type: Ready

- name: "mck : tls : Create server certificate in '{{ mongodb_mck_namespace }}' namespace"
  kubernetes.core.k8s:
    apply: yes
    template: "templates/mck/server-cert.yml"
    wait: yes
    wait_condition:
      status: "True"
      type: Ready

# Taking ca.crt value in a variable
# Mongo needs a configmap having ca.crt value
- name: "mck : install : Lookup the ca.crt"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: mongo-mck-server-cert
    namespace: "{{mongodb_mck_namespace}}"
  register: mongodb_mck_ca_lookup

# Check if configmap exists
- name: "mck : install : Check for existing CA configmap"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ConfigMap
    name: mas-mongo-mck-cert-map
    namespace: "{{ mongodb_mck_namespace }}"
  register: ca_cfgmap_info

# Creating a ca.crt configmap which will be consumed by mongo cr
- name: "mck : install : Create new ca configmap"
  when:
    - ca_cfgmap_info.resources is defined
    - ca_cfgmap_info.resources | length == 0
  vars:
    mongodb_mck_ca_crt: "{{ mongodb_mck_ca_lookup.resources[0].data['ca.crt'] | b64decode }}"
  kubernetes.core.k8s:
    apply: yes
    template: "templates/mck/tls.yml"

# 8. Create MongoDb admin user credentials secret
# -----------------------------------------------------------------------------
- name: "mck: install : Check for existing user password secret"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: mas-mongo-mck-admin-password
    namespace: "{{ mongodb_mck_namespace }}"
  register: admin_password_info

- name: "mck : install : Create new MongoDB admin user credentials secret"
  when:
    - admin_password_info.resources is defined
    - admin_password_info.resources | length == 0
  kubernetes.core.k8s:
    apply: yes
    template: "templates/mck/admin-password.yml"

# 9. Create MongoDB metrics endpoint secret (MCK)
# -----------------------------------------------------------------------------
- name: "mck : install : Check for existing MongoDB metrics endpoint secret"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: mas-mongo-mck-metrics-endpoint-secret
    namespace: "{{ mongodb_mck_namespace }}"
  register: metrics_endpoint_secret_info


- name: "mck : install : Create new MongoDB metrics endpoint secret"
  when:
    - metrics_endpoint_secret_info.resources is defined
    - metrics_endpoint_secret_info.resources | length == 0
  kubernetes.core.k8s:
    apply: yes
    template: "templates/mck/metrics-endpoint-secret.yml.j2"
  
# 10. Deploy the MongoDB cluster (MCK)
# -----------------------------------------------------------------------------
- name: "mck : install : Deploy MongoDB cluster"
  kubernetes.core.k8s:
    apply: yes
    template: "templates/mck/{{ mongodb_mck_version }}///cr.yml.j2"
  when:
    - mongodb_mck_override_spec or existing_mongodb.resources[0].status.version is not defined

- name: "mck : install : Preserving existing settings if Mongo already installed"
  vars:
    mongodb_mck_cpu_limits: "{{ existing_mongodb.resources[0].spec.statefulSet.spec.template.spec.containers[0].resources.limits.cpu }}"
    mongodb_mck_mem_limits: "{{ existing_mongodb.resources[0].spec.statefulSet.spec.template.spec.containers[0].resources.limits.memory }}"
    mongodb_mck_cpu_requests: "{{ existing_mongodb.resources[0].spec.statefulSet.spec.template.spec.containers[0].resources.requests.cpu }}"
    mongodb_mck_mem_requests: "{{ existing_mongodb.resources[0].spec.statefulSet.spec.template.spec.containers[0].resources.requests.memory }}"
    mongodb_mck_storage_class: "{{ existing_mongodb.resources[0].spec.statefulSet.spec.volumeClaimTemplates[0].spec.storageClassName }}"
    mongodb_mck_storage_capacity_data: "{{ existing_mongodb.resources[0].spec.statefulSet.spec.volumeClaimTemplates[0].spec.resources.requests.storage }}"
    mongodb_mck_storage_capacity_logs: "{{ existing_mongodb.resources[0].spec.statefulSet.spec.volumeClaimTemplates[1].spec.resources.requests.storage }}"
    mongodb_mck_replicas: "{{ existing_mongodb.resources[0].spec.members }}"
  kubernetes.core.k8s:
    apply: yes
    template: "templates/mck/{{ mongodb_mck_version }}///cr.yml.j2"
  when:
    - existing_mongodb.resources[0].status.version is defined
    - not mongodb_mck_override_spec

# 12. Create MongoDb service monitor
# -----------------------------------------------------------------------------
- name: "mck : install : Check for existing service monitor"
  kubernetes.core.k8s_info:
    api_version: monitoring.coreos.com/v1
    kind: ServiceMonitor
    name: mas-mongo-mck-service-monitor
    namespace: "{{ mongodb_mck_namespace }}"
  register: mongomck_servicemonitor_info


- name: "community : install : Create new MongoDb service monitor"
  when:
    - mongoce_servicemonitor_info.resources is defined
    - mongoce_servicemonitor_info.resources | length == 0
  kubernetes.core.k8s:
    apply: yes
    template: "templates/mck/servicemonitor.yml.j2"

# 13. Create MongoDb Grafana dashboard
# -----------------------------------------------------------------------------
- name: Get cluster info
  kubernetes.core.k8s_cluster_info:
  register: api_status
  no_log: true

- name: Determine cluster grafana capabilities
  set_fact:
    supports_grafanav4: "{{
      api_status is defined and
      api_status.apis is defined and
      api_status.apis['integreatly.org/v1alpha1'] is defined }}"
    supports_grafanav5: "{{
      api_status is defined and
      api_status.apis is defined and
      api_status.apis['grafana.integreatly.org/v1beta1'] is defined }}"

- name: "Debug information"
  debug:
    msg:
      - "Cluster supports grafana v4 ........... {{ supports_grafanav4 }}"
      - "Cluster supports grafana v5 ........... {{ supports_grafanav5 }}"

- name: "mck : install : Check for existing Grafana v4 dashboard"
  kubernetes.core.k8s_info:
    api_version: integreatly.org/v1alpha1
    kind: GrafanaDashboard
    name: mongodb-overview
    namespace: "{{ mongodb_mck_namespace }}"
  register: mongoce_grafana_dashboard_info
  when:
    - supports_grafanav4

- name: "community : install : Create new MongoDb Grafana v4 dashboard"
  when:
    - supports_grafanav4
    - mongoce_grafana_dashboard_info.resources is defined
    - mongoce_grafana_dashboard_info.resources | length == 0
  kubernetes.core.k8s:
    apply: yes
    template: "templates/mck/dashboards/mongodb-overview.yml.j2"

- name: "mck : install : Check for existing Grafana v5 dashboard"
  kubernetes.core.k8s_info:
    api_version: grafana.integreatly.org/v1beta1
    kind: GrafanaDashboard
    name: mongodb-overview-v5
    namespace: "{{ mongodb_mck_namespace }}"
  register: mongoce_grafana_dashboard_v5__info
  when:
    - supports_grafanav5

- name: "mck : install : Create new MongoDb Grafana v5 dashboard"
  when:
    - supports_grafanav5
    - mongoce_grafana_dashboard_v5__info.resources is defined
    - mongoce_grafana_dashboard_v5__info.resources | length == 0
  kubernetes.core.k8s:
    apply: yes
    template: "templates/mck/dashboards/mongodb-overview-v5.yml.j2"